### ISSUE TITLE
The YAML file of PPO algorithm training

### ISSUE THREAD

**Issue by xiami1234567890** [hr0nix/omega#10]
Could you please provide the YAML file of PPO algorithm training, millions of thanks!

**Comment by hr0nix** [comment]
Hello!

The implementation of PPO seems to be broken by a recent refactoring. I will fix it and provide an example config for PPO soon.

Keep in mind that in this repo I've been primarily focused on polishing MuZero implementation, PPO has been used mostly for the purpose of testing things before doing anything complicated. I've never tested it on anything harder than random_room_5x5.

**Comment by hr0nix** [comment]
I've fixed the implementation of PPO and added a PPO config for room_5x5 environment in https://github.com/hr0nix/omega/commit/9d8c3c90d288f14be51ffaea94a20b0a3da95ed2

**Comment by xiami1234567890** [comment]
Thanks so much for your great work, it is really helpful.
