### ISSUE TITLE
Use MCTS-in-JAX

### ISSUE THREAD

**Issue by ipsec** [hr0nix/omega#16]
Just an idea.

https://github.com/deepmind/mctx

**Comment by hr0nix** [comment]
Thanks for the suggestion! The problem is though, this repo uses Stochastic MuZero, which needs a support for chance nodes in MCTS, something that mctx currently lacks. If they ever support it, I'd be happy to switch.

**Comment by ipsec** [comment]
Great

**Comment by ipsec** [comment]
Hi Boris,

Mctx now support stochastic muzero.

[Commit here](https://github.com/deepmind/mctx/commit/d428fad3dd2ffb2cc8ed8294baccd059e23f7821)
